In [1]:
import pandas as pd
import numpy as np

In [2]:
ebola = pd.read_csv('../Data/country_timeseries.csv')
ebola.head()

Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone  \
0    1/5/2015  289        2776.0            NaN            10030.0   
1    1/4/2015  288        2775.0            NaN             9780.0   
2    1/3/2015  287        2769.0         8166.0             9722.0   
3    1/2/2015  286           NaN         8157.0                NaN   
4  12/31/2014  284        2730.0         8115.0             9633.0   

   Cases_Nigeria  Cases_Senegal  Cases_UnitedStates  Cases_Spain  Cases_Mali  \
0            NaN            NaN                 NaN          NaN         NaN   
1            NaN            NaN                 NaN          NaN         NaN   
2            NaN            NaN                 NaN          NaN         NaN   
3            NaN            NaN                 NaN          NaN         NaN   
4            NaN            NaN                 NaN          NaN         NaN   

   Deaths_Guinea  Deaths_Liberia  Deaths_SierraLeone  Deaths_Nigeria  \
0         1786.0             NaN              2977.0             NaN   
1         1781.0             NaN              2943.0             NaN   
2         1767.0          3496.0              2915.0             NaN   
3            NaN          3496.0                 NaN             NaN   
4         1739.0          3471.0              2827.0             NaN   

   Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  Deaths_Mali  
0             NaN                  NaN           NaN          NaN  
1             NaN                  NaN           NaN          NaN  
2             NaN                  NaN           NaN          NaN  
3             NaN                  NaN           NaN          NaN  
4             NaN                  NaN           NaN          NaN

In [3]:
ebola_long = ebola.melt(id_vars = ['Date', 'Day'],
                       var_name = 'cd_country',
                       value_name = 'count')

In [4]:
ebola_long.head()

Date  Day    cd_country   count
0    1/5/2015  289  Cases_Guinea  2776.0
1    1/4/2015  288  Cases_Guinea  2775.0
2    1/3/2015  287  Cases_Guinea  2769.0
3    1/2/2015  286  Cases_Guinea     NaN
4  12/31/2014  284  Cases_Guinea  2730.0

In [16]:
#Split the cd_country column into different part

#ebola_long['country'] = ebola_long['cd_country'].str.split('_').str.get(1)
#ebola_long['case_death'] = ebola_long['cd_country'].str.split('_').str.get(0)


In [27]:
ebola_split = ebola_long['cd_country'].str.split('_', expand=True) #Returnss a data frame

In [28]:
#another alternative is to conactenante the columns
ebola_long[['status', 'country']] = ebola_split
ebola_long.head()

Date  Day    cd_country   count status country
0    1/5/2015  289  Cases_Guinea  2776.0  Cases  Guinea
1    1/4/2015  288  Cases_Guinea  2775.0  Cases  Guinea
2    1/3/2015  287  Cases_Guinea  2769.0  Cases  Guinea
3    1/2/2015  286  Cases_Guinea     NaN  Cases  Guinea
4  12/31/2014  284  Cases_Guinea  2730.0  Cases  Guinea

How do we pivot the above table to the original form

In [29]:
weather = pd.read_csv('../Data/weather.csv')

In [30]:
weather.head()
#Varaibles are stored in both rows and columns

id  year  month element  d1    d2    d3  d4    d5  d6  ...  d22   d23  \
0  MX17004  2010      1    tmax NaN   NaN   NaN NaN   NaN NaN  ...  NaN   NaN   
1  MX17004  2010      1    tmin NaN   NaN   NaN NaN   NaN NaN  ...  NaN   NaN   
2  MX17004  2010      2    tmax NaN  27.3  24.1 NaN   NaN NaN  ...  NaN  29.9   
3  MX17004  2010      2    tmin NaN  14.4  14.4 NaN   NaN NaN  ...  NaN  10.7   
4  MX17004  2010      3    tmax NaN   NaN   NaN NaN  32.1 NaN  ...  NaN   NaN   

   d24  d25  d26  d27  d28  d29   d30  d31  
0  NaN  NaN  NaN  NaN  NaN  NaN  27.8  NaN  
1  NaN  NaN  NaN  NaN  NaN  NaN  14.5  NaN  
2  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  

[5 rows x 35 columns]

In [31]:
weather_long = weather.melt(id_vars = ['id','year','month','element'],
            var_name = 'day',
            value_name = 'temp')

In [32]:
weather_long.head()

id  year  month element day  temp
0  MX17004  2010      1    tmax  d1   NaN
1  MX17004  2010      1    tmin  d1   NaN
2  MX17004  2010      2    tmax  d1   NaN
3  MX17004  2010      2    tmin  d1   NaN
4  MX17004  2010      3    tmax  d1   NaN

In [38]:
#convert the element column into individual column
#we will use the pd.Pivot_table

(weather_long.pivot_table(index = ['id', 'year', 'month', 'day'],
                        columns = 'element',
                        values = 'temp').reset_index()
).head()

element       id  year  month  day  tmax  tmin
0        MX17004  2010      1  d30  27.8  14.5
1        MX17004  2010      2  d11  29.7  13.4
2        MX17004  2010      2   d2  27.3  14.4
3        MX17004  2010      2  d23  29.9  10.7
4        MX17004  2010      2   d3  24.1  14.4

writing fuctions in python and applying it to your data frame

In [39]:
def my_fuction(x,y):
    pass

In [40]:
def sq(x):
    return x**2

In [41]:
sq(2)

4

In [45]:
assert sq(3)==9 #basics of unit testing in pyton

In [46]:
def avg_2(x,y):
    return x+y/2

In [48]:
avg_2(4,5)

6.5

In [13]:
import pandas as pd
df = pd.DataFrame({'X': [10,20,30],
                  'Y': [20,30,40]})
df

X   Y
0  10  20
1  20  30
2  30  40

Define a Function that returns the square of a number.

In [14]:
def sq(a):
    return a**2

In [15]:
df['X'].apply(sq) #Applies the sq(x) function to column X in df.

0    100
1    400
2    900
Name: X, dtype: int64

In [16]:
def my_exp(x,e):
    return x**e
    

In [17]:
df['Y'].apply(my_exp, e=3)

0     8000
1    27000
2    64000
Name: Y, dtype: int64

In [58]:
def print_me(x):
    print(x)

In [59]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [60]:
def avg_3(x,y,z):
    return x+y+z/3

In [63]:
df.apply(avg_3)#Apply works column by column

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

some funtions are already vectorized

In [64]:
def avg_3_apply(col):
    return np.mean(col)

In [71]:
print('the mean values of a and b are:', df.apply(avg_3_apply))

the mean values of a and b are: a    20.0
b    30.0
dtype: float64


In [76]:
def avg_3(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x+y+z)/3

In [77]:
df.apply(avg_3)

a    20.0
b    30.0
dtype: float64

In [80]:
def avg_2_mod(x,y):
    if(x==20):
        return np.nan
    else:
        return(x+y)/2

In [81]:
#you can vectorize the functions using th np.vectorize()
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [82]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [83]:
df

a   b
0  10  20
1  20  30
2  30  40

In [84]:
#you can also use a python decorator @np.vectorize
@np.vectorize
def avg_2_mod(x,y):
    if(x==20):
        return np.nan
    else:
        return(x+y)/2

In [85]:
avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [87]:
import numba
#for numeric calculation and it's faster

In [88]:
@numba.vectorize
def avg_2_mod_numba(x,y):
    if(x==20):
        return np.nan
    else:
        return(x+y)/2

In [89]:
avg_2_mod_numba(df['a'].values, df['b'].values)
#numba only works with numpy arrays

array([15., nan, 35.])

In [90]:
%%timeit
avg_2_mod(df['a'], df['b'])

70.2 µs ± 4.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [91]:
%%timeit
avg_2_mod_numba(df['a'].values, df['b'].values)

6.4 µs ± 19.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
